# Base image (balenalib raspberry debian bookworm)
FROM balenalib/raspberrypi5-debian:bookworm

# Install pakages
RUN apt-get update && apt-get install -y \
    locales \
    build-essential \
    cmake \
    gcc-arm-none-eabi \
    libnewlib-arm-none-eabi \
    gdb-multiarch \
    openssh-server \
    sudo \
    vim \
    nano \
    gdb \
    git 

# Generate and set Swedish locale
RUN echo "sv_SE.UTF-8 UTF-8" >> /etc/locale.gen && \
    locale-gen sv_SE.UTF-8 && \
    dpkg-reconfigure --frontend=noninteractive locales && \
    update-locale LANG=sv_SE.UTF-8 LC_ALL=sv_SE.UTF-8

# Set environment variables
ENV LANG=sv_SE.UTF-8
ENV LC_ALL=sv_SE.UTF-8

# Verify locale is set
RUN locale
    
# Create the SSH run directory
RUN mkdir /var/run/sshd

# Configure SSH settings (password but no root)
RUN sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin no/' /etc/ssh/sshd_config && \
    sed -i 's/#PasswordAuthentication yes/PasswordAuthentication yes/' /etc/ssh/sshd_config


# Create user and set password using arguments during build
ARG USERNAME=username
ARG PASSWORD=password
RUN useradd -m -s /bin/bash ${USERNAME} && \
    echo "${USERNAME}:${PASSWORD}" | chpasswd && \
    usermod -aG sudo ${USERNAME}

# Create ws directory and .vimrc in the user's home directory
run mkdir -p /home/${username}/ws && chown ${username}:${username} /home/${username}/ws && \
    echo -e 'set nocompatible\nsyntax on\nfiletype plugin indent on' >> /home/${username}/.vimrc && \
    chown ${username}:${username} /home/${username}/.vimrc


# Expose SSH port
EXPOSE 22

# Copy en set entrypoint script
COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

# Set the entrypoint
ENTRYPOINT ["/entrypoint.sh"]

# Keep the container running indefinetly
# CMD ["tail", "-f", "/dev/null"]
CMD ["/usr/sbin/sshd", "-D"]
